### ISSUE TITLE
[SUGGESTION] Split generated files

### ISSUE THREAD

**Issue by FrozenInc** [FlixCoder/fhir-sdk#14] opened 2023-10-13 12:01 UTC
Hi, I'm wondering if it would be better to split the generated files in multiple files so that the compiler can handle them without taking 8+ GBs of RAM to compile.

**Comment by FlixCoder** [comment] 2023-10-13 12:15
Hi, thank you for the suggestion.

However, I have tried it and it doesn't seem to help. I have tried separate files, separate crates (not entirely possible) and more, whatever I try, it keeps using the same amount.
The reason it takes so much memory is mostly due to serde, typed builder and the big amount of big types, so I don't think it can be solved that easily. It seems to be some kind of indexing in the crate's surface maybe?

**Comment by FrozenInc** [comment] 2023-10-13 18:14
Hmm interesting.

I saw that recently serde bundled some of their things in a compiled lib form to speed up compile times. Would it possibly be a good idea to do something similar, where you can build the model lib into a fully compiled form, and then just reference it? So that the model lib build only happens once and can be reused during development+CI/CD.

**Comment by FlixCoder** [comment] 2023-10-13 18:26
I don't think that would be possible for a library as it needs to ne source to be accepted by cargo. I also don't think it would help compile time sadly, as the reexporting of all types results in similar issues.. 
and lastly shipping a binary didn't receive a lot of good attention and probably is not desirable by most users

**Comment by FlixCoder** [comment] 2023-10-13 18:53
Oh ok. That is actually why the fhir-sdk crate is separate from fhir-model, so that it only needs to compile once and is faster and supposedly less memory, but well, it is still using memory sadly for some reason. I made an issue on the Rust project, but I have no idea if it is possible to fix.

I you find a way to reduce memory usage and compile time I would be happy to hear it (without reducing functionality of course).

I also can't have CI because of it and I am not happy about it :D

**Comment by FrozenInc** [comment] 2023-11-11 00:12
Hi again!

I read up a bit more about Rust and did 1 test that generated very promising result!

Turns out that the typed-builder lib is one of the culprits for the insane build times+RAM usage during compile.

I only tried with fhir-models, as removing it might require modifications to fhir-sdk.

My results ran with DEBUG, RELEASE had similar results:
| With/Without| Ram usage| Compile time|
|--------|--------|--------|
| With Typed builder| 11 500 MB RAM| 3m 19s|
| Without Typed builder| 4900 MB RAM| 1m 29s|


Now I understand that the typed-builder lib is used for creating the resource that are used, but I think that instead declaring them as just a normal struct + `impl Default ` for every type, should be able to solve the same issue.

BTW thanks for the great work!

**Comment by FlixCoder** [comment] 2023-11-11 07:58
Hi, thanks!

That is why you can disable the builders feature :D The problem is, you can not really have Default implementations, as there are required fields.

I used to think about derive_builder instead of typed-builder, as that uses no generics and should reduce compile resources too. But that then needs plenty of annoying error handling, so I prefer this.

If you have no serde and no builders it compiled in 20 seconds on my machine, but both of them are needed imo. Builders can be disabled via feature flag already if you don't want them. But without serde is kind of pointless using FHIR. It would somehow need more a compiler friendly serde implementation.

**Comment by FlixCoder** [comment] 2024-01-13 13:05
Closing in favor of https://github.com/FlixCoder/fhir-sdk/issues/17

**Closed by FlixCoder** 2024-01-13 13:05 UTC
